CREATE TABLE "system_settings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "system_settings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"system_name" text DEFAULT 'Lazarus CG - Sistema de Controle' NOT NULL,
	"institution" text DEFAULT 'Unidade Prisional - Manaus/AM' NOT NULL,
	"admin_name" text DEFAULT 'Lazarus' NOT NULL,
	"timezone" text DEFAULT 'america/manaus' NOT NULL,
	"language" text DEFAULT 'pt-br' NOT NULL,
	"urgent_days" integer DEFAULT 2 NOT NULL,
	"warning_days" integer DEFAULT 7 NOT NULL,
	"auto_archive" boolean DEFAULT true NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL
);
